global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'prod-monitor'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

rule_files:
  - '/etc/prometheus/rules.yml'
  - '/etc/prometheus/alerts.yml'

scrape_configs:
  - job_name: 'prometheus-service'
    static_configs:
      - targets: ['192.168.50.4:9090']  

  - job_name: 'tpfoyer-devops-service'
    scheme: 'http'
    metrics_path: '/tpfoyer/actuator/prometheus'
    static_configs: 
    - targets:
      - '192.168.50.4:8087'
      labels:
        group: 'tpfoyer-API'
